"""
wiring.py — Emit deterministic wiring-test stubs for scaffolded routes/modules.

A scaffolder's worst failure is the Potemkin route: a handler that returns
200 OK but is wired to nothing — never registered on the app, never persisting
the row it claims to. It survives because nothing tests the *wiring*, only the
shape. These stubs make that impossible: alongside each scaffolded route (and
service module) ``develop.py`` drops a test that

  * imports the handler module and asserts each handler function exists — runs
    immediately, so a broken or empty scaffold fails at once; and
  * carries a ``*_unverified`` tripwire per route that FAILS on purpose until a
    human confirms the route is registered and (for writes) actually persists a
    row. A fresh scaffold is therefore *loud-red-unverified*, not
    silently-green-unwired.

Deterministic and local — no Ollama. Built entirely from the build plan's
structured ``api_routes`` and file specs, so the tripwire text is precise
(method, path, handler, models) without a model guessing. Python only for now
(the plan is Python-oriented); other languages get nothing rather than a wrong
guess, matching ``orphans.py``.

The emitted tests are pytest-style (the default Python test framework, and what
``detect.py`` reports for Python projects). They live under ``<tests>/wiring/``
so you can run or skip them as a group by path: ``pytest tests/wiring`` /
``pytest --ignore=tests/wiring``.
"""

import json

WRITE_METHODS = {"POST", "PUT", "PATCH", "DELETE"}


# ---------------------------------------------------------------------------
# Path / name helpers
# ---------------------------------------------------------------------------
def _norm_rel(path):
    if not isinstance(path, str) or not path.strip():
        return None
    return path.strip().lstrip("/\\").replace("\\", "/").lstrip("./")


def _module_path(rel):
    stem = rel[:-3] if rel.endswith(".py") else rel
    return stem.replace("/", ".")


def _collapse(text):
    """Non-alnum runs -> single '_', trimmed. Keeps generated names readable."""
    out = "".join(c if c.isalnum() else "_" for c in str(text))
    while "__" in out:
        out = out.replace("__", "_")
    return out.strip("_")


def _flatten(rel):
    stem = rel[:-3] if rel.endswith(".py") else rel
    return _collapse(stem)


def _slug(text):
    return _collapse(text) or "x"


def _clean(name):
    """A model/handler name that is real, or None for null/empty placeholders."""
    if not isinstance(name, str):
        return None
    n = name.strip()
    return n if n and n.lower() not in ("null", "none", "n/a", "") else None


# ---------------------------------------------------------------------------
# Route wiring test
# ---------------------------------------------------------------------------
_ROUTE_HEADER = '''"""
Wiring stubs for __HANDLER_FILE__ -- GENERATED by `drop.py develop`.

Asserts the scaffolded route is actually WIRED, not a 200-OK facade:
  - the handler module imports and each handler function exists (runs now)
  - each route is registered on the app and, for writes, persists a row
    (complete or delete the *_unverified tripwire below)

The *_unverified tests FAIL on purpose: a fresh scaffold is unverified until a
human confirms the wiring. Fill in the TODO so it checks automatically, or delete
the test once you have verified it by hand. Deleting it *without* checking simply
recreates the Potemkin scaffold this guards against.

Run/skip wiring stubs as a group by path: `pytest __TESTS_DIR__/wiring`.
"""
import importlib

import pytest


def _load():
    try:
        return importlib.import_module(MODULE)
    except Exception as e:  # a wiring failure, reported cleanly, not a collection crash
        pytest.fail(f"handler module {MODULE!r} does not import -- scaffold not wired: {e}")


def test_handler_module_imports():
    _load()
'''

_HANDLER_TEST = '''

@pytest.mark.parametrize("fn", HANDLERS)
def test_handler_function_defined(fn):
    mod = _load()
    assert hasattr(mod, fn) and callable(getattr(mod, fn)), (
        f"{MODULE}.{fn} is declared as a route handler but is missing or not callable")
'''


def _route_checklist(method, request_model, response_model):
    """Return (comment lines, short failure phrase) for a route's tripwire."""
    m = method.upper()
    reg = "the route is REGISTERED on the app (a defined-but-unrouted function still 'exists')"
    if m in ("POST", "PUT", "PATCH"):
        persist = "a successful call PERSISTS a row -- query the table/store and assert it is there"
        extra = []
        if request_model:
            extra.append("request body: " + request_model)
        if response_model:
            extra.append("response: " + response_model)
        if extra:
            persist += "  (" + "; ".join(extra) + ")"
        return [reg, persist], "route not verified to persist a row"
    if m == "DELETE":
        return [reg, "a successful call REMOVES the target row -- assert it is gone afterwards"], \
               "route not verified to remove the row"
    # read methods
    resp = "a request returns the expected status" + (
        " and response_model (" + response_model + ")" if response_model else "")
    return [reg, resp], "route not verified as registered and responding"


def _route_tripwire(route, used_names):
    method = (route.get("method") or "GET").upper()
    path = route.get("path") or "/"
    handler = _clean(route.get("handler_function")) or "?"
    request_model = _clean(route.get("request_model"))
    response_model = _clean(route.get("response_model"))

    name = f"test_wiring_{_slug(method)}_{_slug(path)}_unverified"
    while name in used_names:            # disambiguate collisions deterministically
        name += "_x"
    used_names.add(name)

    checklist, short = _route_checklist(method, request_model, response_model)
    fail_msg = (f"WIRING NOT VERIFIED: {method} {path} -> {handler} -- {short}. "
                f"Verify via the app test client, then delete this test.")

    lines = [f"def {name}():"]
    lines.append("    # POTEMKIN TRIPWIRE -- verify, then delete this test.")
    lines.append(f"    # {method} {path}  ->  {handler}")
    lines.append("    # Assert that:")
    for c in checklist:
        lines.append("    #   - " + c)
    lines.append("    pytest.fail(" + json.dumps(fail_msg) + ")")
    return "\n".join(lines)


def _route_test_file(handler_file, routes, tests_dir):
    module = _module_path(handler_file)
    handlers = []
    for r in routes:
        fn = _clean(r.get("handler_function"))
        if fn and fn not in handlers:
            handlers.append(fn)

    body = (_ROUTE_HEADER
            .replace("__HANDLER_FILE__", handler_file)
            .replace("__TESTS_DIR__", tests_dir))
    parts = [
        f"MODULE = {json.dumps(module)}\n"
        f"HANDLERS = {json.dumps(handlers)}\n\n",
        body,
    ]
    if handlers:
        parts.append(_HANDLER_TEST)

    used_names = set()
    for r in routes:
        parts.append("\n\n" + _route_tripwire(r, used_names))
    return "".join(parts).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Service / module reachability test
# ---------------------------------------------------------------------------
_MODULES_HEADER = '''"""
Module wiring stubs -- GENERATED by `drop.py develop`.

Each scaffolded module must import and expose the API the plan declared for it.
A broken import or an empty/renamed symbol fails here, so a service scaffold that
exists but wires nothing cannot pass silently. (Whether anything in *production*
imports the module is a separate check -- see `drop.py detect`'s orphan report.)

Run/skip wiring stubs as a group by path: `pytest __TESTS_DIR__/wiring`.
"""
import importlib

import pytest


@pytest.mark.parametrize("module", sorted(MODULES))
def test_module_wired(module):
    try:
        mod = importlib.import_module(module)
    except Exception as e:
        pytest.fail(f"{module} does not import -- scaffold not wired or deps missing: {e}")
    missing = [s for s in MODULES[module] if not hasattr(mod, s)]
    assert not missing, (
        f"{module} is missing declared symbols {missing} -- empty or renamed scaffold")
'''


def _modules_test_file(specs, tests_dir):
    mapping = {module: symbols for module, symbols in specs}
    header = _MODULES_HEADER.replace("__TESTS_DIR__", tests_dir)
    return (f"MODULES = {json.dumps(mapping, indent=4, sort_keys=True)}\n\n"
            + header).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def build_wiring_tests(plan, generated_paths=None, tests_dir="tests", lang="python"):
    """Return ``{test_rel_path: content}`` of wiring stubs for a build plan.

    *generated_paths*, when given, restricts output to routes/modules whose
    source file was actually scaffolded this run (so ``--layer`` filtering and
    dry-runs stay consistent). Returns ``{}`` for non-Python plans or when there
    is nothing to wire.
    """
    if lang != "python" or not isinstance(plan, dict):
        return {}

    gen = None if generated_paths is None else {_norm_rel(p) for p in generated_paths}
    tests_dir = (tests_dir or "tests").rstrip("/")

    # Group routes by handler file.
    routes_by_file = {}
    for r in plan.get("api_routes") or []:
        if not isinstance(r, dict):
            continue
        hf = _norm_rel(r.get("handler_file"))
        if not hf or not hf.endswith(".py"):
            continue
        if gen is not None and hf not in gen:
            continue
        routes_by_file.setdefault(hf, []).append(r)

    out = {}
    for hf in sorted(routes_by_file):
        path = f"{tests_dir}/wiring/test_wiring_{_flatten(hf)}.py"
        out[path] = _route_test_file(hf, routes_by_file[hf], tests_dir)

    # Service/module reachability for scaffolded modules that aren't route
    # handlers (those are already covered above) and aren't packaging files.
    route_files = set(routes_by_file)
    specs = []
    for layer in plan.get("layers") or []:
        if not isinstance(layer, dict):
            continue
        for f in layer.get("files") or []:
            if not isinstance(f, dict):
                continue
            p = _norm_rel(f.get("path"))
            if not p or not p.endswith(".py") or p in route_files:
                continue
            if gen is not None and p not in gen:
                continue
            base = p.rsplit("/", 1)[-1]
            if base in ("__init__.py", "conftest.py", "setup.py", "__main__.py"):
                continue
            symbols = [s for s in (list(f.get("key_classes") or [])
                                   + list(f.get("key_functions") or []))
                       if _clean(s)]
            specs.append((_module_path(p), symbols))
    if specs:
        specs.sort()
        out[f"{tests_dir}/wiring/test_wiring_modules.py"] = _modules_test_file(specs, tests_dir)

    return out
