"""
triggers.py — Local enforcement triggers (git hooks + CI), so the gates run
without anyone remembering to run them.

The gate pack (``layers``, ``invariants``, ``golden``) is only leverage if it
*fires*. Today nothing runs unless a human types the command. This installs the
fast, air-gapped, fail-closed gates as a **pre-commit hook** (blocks a bad
commit locally) and emits a **CI workflow** (blocks a bad push/PR) — the
"event-driven" property from the harness reframe (TODO.md).

Only the deterministic, no-Ollama gates are wired: ``layers``, ``invariants``,
``golden``. They exit non-zero on violation and opt out cleanly (exit 0) when a
repo hasn't configured them, so the same hook is safe to install everywhere. The
advisory reports (orphans/claims via ``detect``) stay out of the blocking path —
they're print-only by design (false-negative bias) and ``detect`` needs the
engine, so they don't belong in an air-gapped commit hook.

Sovereignty constraint: the pre-commit hook needs no network and no Ollama — it
runs stdlib-only Python over the working tree. The toolkit path is baked into the
hook at install time (``{python}``/``{drop}`` resolve to the interpreter and
``drop.py`` that ran ``drop.py hooks``); re-run the command to refresh after
moving the toolkit.
"""

import os
import shutil

MARKER = "dropin-AI-Toolkit pre-commit gate"

# Gate name -> config filenames that mean "this repo opted in". The hook only
# invokes a gate whose config is present, so an unconfigured repo sees no noise.
GATES = (
    ("layers", (".layers.json", "layers.json")),
    ("invariants", (".invariants.py",)),
    ("golden", (".golden.json", "golden.json")),
)


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------
_PRECOMMIT_TEMPLATE = """\
#!/bin/sh
# {marker} — installed by `drop.py hooks`. Do not edit by hand; re-run
#   python "{drop}" hooks
# to refresh (e.g. after moving the toolkit). Bypass once with:
#   DROPIN_SKIP=1 git commit ...
#
# Runs the fast, air-gapped, fail-closed gates over the working tree, but only
# for the gates this repo has configured. No Ollama, no network.
set -u
if [ "${DROPIN_SKIP:-0}" = "1" ]; then
    exit 0
fi

PY="{python}"
DROP="{drop}"
ROOT="$(git rev-parse --show-toplevel)"
status=0

run_gate() {
    gate="$1"
    shift
    for cfg in "$@"; do
        if [ -e "$ROOT/$cfg" ]; then
            "$PY" "$DROP" "$gate" --project "$ROOT" || status=1
            return
        fi
    done
}

run_gate layers      .layers.json layers.json
run_gate invariants  .invariants.py
run_gate golden      .golden.json golden.json

if [ "$status" -ne 0 ]; then
    echo "" 1>&2
    echo "dropin gates failed — commit blocked. Fix the above, or bypass once with:" 1>&2
    echo "    DROPIN_SKIP=1 git commit ..." 1>&2
fi
exit $status
"""


_CI_TEMPLATE = """\
# dropin-AI-Toolkit gates — generated by `drop.py hooks --ci`.
# Runs the fast, air-gapped, fail-closed gates (layers, invariants, golden) on
# every push and PR. Deterministic, stdlib-only — no Ollama, no network.
#
# These gates live in the dropin-AI-Toolkit, so CI needs drop.py on disk. Pick
# ONE strategy below and delete the other:
#   (A) check the toolkit out alongside this repo — set `repository:` to your
#       toolkit's slug (shown), or
#   (B) vendor the toolkit (drop.py + gates/ + generation/) into this repo and
#       point DROPIN_HOME at that folder (drop the extra checkout step).
name: dropin-gates
on: [push, pull_request]
jobs:
  gates:
    runs-on: ubuntu-latest
    env:
      DROPIN_HOME: ${{ github.workspace }}/.dropin-toolkit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: OWNER/dropin-AI-Toolkit   # <-- set your toolkit slug
          path: .dropin-toolkit
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Architectural layer gate
        run: python "$DROPIN_HOME/drop.py" layers --project .
      - name: Design-invariant harness
        run: python "$DROPIN_HOME/drop.py" invariants --project .
      - name: Golden-file regression gate
        run: python "$DROPIN_HOME/drop.py" golden --project .
"""


def render_precommit(python, drop):
    """The pre-commit hook body with the interpreter and drop.py path baked in.

    Uses plain string replacement (not ``str.format``) so the shell ``${...}``
    and ``{ }`` in the template survive untouched.
    """
    return (_PRECOMMIT_TEMPLATE
            .replace("{marker}", MARKER)
            .replace("{python}", python)
            .replace("{drop}", drop))


def render_ci():
    """The GitHub Actions workflow body (no substitution needed)."""
    return _CI_TEMPLATE


# ---------------------------------------------------------------------------
# Install
# ---------------------------------------------------------------------------
def _hooks_dir(root):
    """Resolve the git hooks dir for *root*, or None if it isn't a repo.

    Handles the common ``.git/`` directory and the worktree/submodule case where
    ``.git`` is a ``gitdir:`` pointer file. Stdlib-only — no ``git`` subprocess,
    so it stays hermetic and works air-gapped.
    """
    git = os.path.join(root, ".git")
    if os.path.isdir(git):
        return os.path.join(git, "hooks")
    if os.path.isfile(git):
        try:
            with open(git, "r", encoding="utf-8") as fh:
                line = fh.read().strip()
        except OSError:
            return None
        if line.startswith("gitdir:"):
            gitdir = line.split(":", 1)[1].strip()
            if not os.path.isabs(gitdir):
                gitdir = os.path.normpath(os.path.join(root, gitdir))
            return os.path.join(gitdir, "hooks")
    return None


def install_precommit(root, python, drop, force=False):
    """Write the pre-commit hook. Returns a result dict.

    Fail-closed on surprises: a foreign existing hook is *not* clobbered without
    ``force`` (it's backed up to ``pre-commit.dropin-backup`` first); a
    previously-installed dropin hook is refreshed in place (idempotent).
    """
    hooks = _hooks_dir(root)
    if not hooks:
        return {"ok": False, "action": "pre-commit",
                "error": f"not a git repository (no .git found under {root})"}
    os.makedirs(hooks, exist_ok=True)
    path = os.path.join(hooks, "pre-commit")
    backed_up = None
    if os.path.exists(path):
        try:
            with open(path, "r", encoding="utf-8") as fh:
                existing = fh.read()
        except (OSError, UnicodeDecodeError):
            existing = ""
        ours = MARKER in existing
        if not ours:
            if not force:
                return {"ok": False, "action": "pre-commit", "path": path,
                        "error": "a non-dropin pre-commit hook already exists; "
                                 "re-run with --force to back it up and replace it"}
            backed_up = path + ".dropin-backup"
            shutil.copyfile(path, backed_up)
    # newline="\n": a CRLF shebang line breaks the hook on POSIX shells.
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(render_precommit(python, drop))
    try:
        os.chmod(path, 0o755)
    except OSError:
        pass  # Windows/filesystems without exec bits — git uses the shebang
    return {"ok": True, "action": "pre-commit", "path": path,
            "backed_up": backed_up, "refreshed": backed_up is None and os.path.exists(path)}


def install_ci(root, force=False):
    """Write .github/workflows/dropin-gates.yml. Returns a result dict."""
    wf_dir = os.path.join(root, ".github", "workflows")
    path = os.path.join(wf_dir, "dropin-gates.yml")
    if os.path.exists(path) and not force:
        return {"ok": False, "action": "ci", "path": path,
                "error": "workflow already exists; re-run with --force to overwrite"}
    os.makedirs(wf_dir, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(render_ci())
    return {"ok": True, "action": "ci", "path": path}


def run_hooks(root, python, drop, ci=False, force=False):
    """Install the pre-commit hook (and CI workflow when *ci*). Returns a result
    dict with per-action results and an aggregate ``ok``."""
    root = os.path.abspath(root)
    results = [install_precommit(root, python, drop, force=force)]
    if ci:
        results.append(install_ci(root, force=force))
    return {"ok": all(r["ok"] for r in results), "root": root, "results": results}


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------
def print_hooks(result):
    """Pretty-print the install run for `drop.py hooks`."""
    print(f"\n  Triggers — {result['root']}")
    for r in result["results"]:
        action = r["action"]
        if not r["ok"]:
            print(f"    [FAIL]  {action}: {r.get('error', 'unknown error')}")
            continue
        rel = os.path.relpath(r["path"], result["root"])
        if r.get("backed_up"):
            print(f"    [OK]    {action}: installed {rel} "
                  f"(existing hook backed up to {os.path.basename(r['backed_up'])})")
        else:
            print(f"    [OK]    {action}: installed {rel}")

    if result["ok"]:
        print("\n    Triggers installed — gates now run on every commit"
              " (set DROPIN_SKIP=1 to bypass once).")
    else:
        print("\n    Trigger install: FAILED (see above)")
